@id=0195f590-eb92-788c-a36f-ad04f7796f11
@permission_id=0195f58e-4636-7db8-b5ac-60fdca1ef428
@code=ROLE_PERMISSION_2
@name=PERMISSION_1
@description=PERMISSION_1

###

GET {{base_url}}/v1/roles/code/{{code}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/roles/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/roles/search
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/roles
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "id": "{{id}}",
  "code": "{{code}}",
  "name": "{{name}}",
  "description": "{{description}}",
  "permissionIds": ["{{permission_id}}"]
}
