@id=
@permission_id=
@code=
@name=
@description=

###

GET {{base_url}}/v1/roles/code/{{code}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/roles/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/roles/search
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/roles
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "id": "{{id}}",
  "code": "{{code}}",
  "name": "{{name}}",
  "description": "{{description}}",
  "permissionIds": ["{{permission_id}}"]
}
