FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY gradle gradle
COPY gradlew build.gradle settings.gradle ./
RUN chmod +x ./gradlew
RUN ./gradlew dependencies --no-daemon
COPY src src
RUN ./gradlew clean build --no-daemon

FROM eclipse-temurin:21-jre-alpine AS deploy
WORKDIR /app
COPY --from=build /app/build/libs/sbt.jar sbt.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/sbt.jar"]