services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/demo
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - server
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
    networks:
      - server
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: redis
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    networks:
      - server
    restart: unless-stopped

networks:
  server:
    driver: bridge

volumes:
  postgres-data:
    driver: local